name: check test and install


on: [pull_request]


jobs:
  build:
    runs-on: [ubuntu-latest]
    name: "Build and test"
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      #- name: Restore Node Modules
      #id: cache-lerna
      #uses: actions/cache@master
      #with:
      #path: |
      #node_modules
      #*/*/node_modules
      #key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn install
